version: '3.8'

services:
  app:
    build: .
    container_name: TelegramBot
    command: python app.py  # или другая команда для запуска твоего приложения
    volumes:
      - .:/
      - .:/data
    environment:
      - DATABASE_PATH=./data/database.db
    ports:
      - "8000:8000"  # Пример порта, на котором будет работать твое приложение
    user: "1000:1000"
    depends_on:
      - redis  # Указываем зависимость от Redis

  redis:
    image: "redis:alpine"
    container_name: redis-db
    ports:
      - "6379:6379"  # Порт Redis
